### ISSUE TITLE
Not able to run `npm test` command

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#1222]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```
I  developed a clarity-angular component - clr-list and I am trying to test it but I have problems running npm test command. It fails with messages which I could not debug. It will be great if you can suggest a solution.

### Expected behavior
Be able to run `npm test` command with no errors

### Actual behavior
running the `npm test` command fails with karma exit code 1 

### Reproduction of behavior
`vasil@rabotlivko:~/server/clarity$ npm test`
```
> clarity-all@0.10.0-alpha.5 test /home/vasil/server/clarity
> gulp test

[23:33:24] Using gulpfile ~/server/clarity/gulpfile.js
[23:33:24] Starting 'test'...
[23:33:24] Starting 'build'...
[23:33:24] Starting 'clean'...
[23:33:24] Finished 'clean' after 571 ms
[23:33:24] Starting 'sass:static'...
[23:33:24] Starting 'sass:clarity'...
[23:33:24] Starting 'sass:app'...
[23:33:24] Starting 'sass:icons'...
[23:33:24] Starting 'typescript'...
[23:33:24] Starting 'tslint:clarity'...
[23:33:24] Starting 'tslint:app'...
[23:33:24] Starting 'tslint:icons'...
[23:33:24] Starting 'tslint:tests'...
[23:33:24] Starting 'html:index'...
[23:33:24] Starting 'html:app'...
[23:33:24] Starting 'html:assets'...
[23:33:24] Starting 'typescript:icons'...
[23:33:24] Starting 'typescript:clarity'...
[23:33:30] Finished 'sass:icons' after 5.41 s
[23:33:30] Finished 'sass:clarity' after 5.5 s
[23:33:30] Finished 'sass:static' after 5.53 s
[23:33:31] Finished 'html:index' after 6.21 s
[23:33:31] Finished 'html:assets' after 7.05 s
[23:33:36] Finished 'tslint:icons' after 12 s
[23:33:45] Finished 'typescript:icons' after 20 s
[23:33:45] Starting 'bundle:icons:sfx'...
[23:33:46] Starting 'bundle:icons-lite:sfx'...
[23:33:46] Finished 'bundle:icons-lite:sfx' after 2.98 ms
[23:33:46] Starting 'bundle:icons:shapes'...
[23:33:46] Finished 'bundle:icons:shapes' after 3.08 ms
[23:33:46] Starting 'svg:icons'...
Completed writing core-shapes svg files
Completed writing commerce-shapes svg files
Completed writing essential-shapes svg files
Completed writing media-shapes svg files
Completed writing social-shapes svg files
Completed writing technology-shapes svg files
Completed writing travel-shapes svg files
[23:33:48] Finished 'svg:icons' after 2.37 s
[23:33:48] Starting 'svg:icons:zip'...
[23:33:53] Finished 'bundle:icons:sfx' after 8.15 s
[23:34:00] Finished 'tslint:tests' after 36 s
[23:34:02] Finished 'sass:app' after 37 s
[23:34:02] Starting 'sass'...
[23:34:02] Finished 'sass' after 62 μs
[23:34:05] Finished 'tslint:clarity' after 41 s
[23:34:11] Finished 'tslint:app' after 47 s
[23:34:11] Starting 'tslint'...
[23:34:11] Finished 'tslint' after 45 μs
[23:34:11] Starting 'typescript:icons'...
[23:34:11] Starting 'typescript:app'...
[23:34:11] Starting 'typescript:tests'...
[23:34:11] Starting 'typescript:tests:icons'...
[23:34:12] Finished 'typescript:tests:icons' after 760 ms
[23:34:13] Finished 'html:app' after 48 s
[23:34:13] Starting 'html'...
[23:34:13] Finished 'html' after 35 μs
[23:34:13] Finished 'typescript:icons' after 1.43 s
[23:34:17] Finished 'typescript:tests' after 6.17 s
[23:34:21] Finished 'typescript:clarity' after 57 s
[23:34:21] Starting 'bundle:clarity:js'...
[23:34:30] Finished 'bundle:clarity:js' after 8.78 s
[23:34:30] Starting 'bundle:zip'...
[23:34:30] Finished 'bundle:zip' after 33 ms
[23:34:30] Starting 'bundle'...
[23:34:30] Finished 'bundle' after 345 μs
[23:34:30] Finished 'svg:icons:zip' after 42 s
[23:34:30] Starting 'svg'...
[23:34:30] Finished 'svg' after 44 μs
[23:34:30] Finished 'typescript:app' after 19 s
[23:34:30] Finished 'typescript' after 1.08 min
[23:34:30] Finished 'build' after 1.1 min
[23:34:30] Starting 'karma:verbose'...

[4m[1mSTART:[22m[24m
[33m27 07 2017 23:34:31.300:WARN [watcher]: [39mPattern "/home/vasil/server/clarity/dist/**/*.js.map" does not match any file.
[32m27 07 2017 23:34:31.800:INFO [karma]: [39mKarma v1.7.0 server started at http://0.0.0.0:9876/
[32m27 07 2017 23:34:31.800:INFO [launcher]: [39mLaunching browser Chrome_Headless with unlimited concurrency
[32m27 07 2017 23:34:31.809:INFO [launcher]: [39mStarting browser Chrome
[32m27 07 2017 23:34:32.264:INFO [HeadlessChrome 0.0.0 (Linux 0.0.0)]: [39mConnected on socket -yMyPMBmFdRJujQaAAAA with id 41303491
[33m27 07 2017 23:34:33.277:WARN [web-server]: [39m404: /base/selenium-webdriver/testing
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  {
    "originalErr": {
      "__zone_symbol__currentTask": {
        "type": "microTask",
        "state": "notScheduled",
        "source": "Promise.then",
        "zone": "<root>",
        "cancelFn": null,
        "runCount": 0
      }
    },
    "__zone_symbol__currentTask": {
      "type": "microTask",
      "state": "notScheduled",
      "source": "Promise.then",
      "zone": "<root>",
      "cancelFn": null,
      "runCount": 0
    }
  }

[32mFinished in 2.341 secs / 0 secs @ 23:34:34 GMT+0300 (EEST)[39m

[4m[1mSUMMARY:[22m[24m
[32m[32m✔[32m 0 tests completed[39m
[[90m23:34:34[39m] '[36mkarma:verbose[39m' [31merrored after[39m [35m3.89 s[39m
[[90m23:34:34[39m] Error: There are failing unit tests
    at /home/vasil/server/clarity/build/tasks/karma.js:32:27
    at removeAllListeners (/home/vasil/server/clarity/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (/home/vasil/server/clarity/node_modules/karma/lib/server.js:391:9)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1577:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[[90m23:34:34[39m] '[36mtest[39m' [31merrored after[39m [35m1.17 min[39m
[[90m23:34:34[39m] [31mError[39m in plugin '[36mrun-sequence(karma:verbose)[39m'
Message:
    There are failing unit tests
Stack:
Error: There are failing unit tests
    at /home/vasil/server/clarity/build/tasks/karma.js:32:27
    at removeAllListeners (/home/vasil/server/clarity/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (/home/vasil/server/clarity/node_modules/karma/lib/server.js:391:9)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1577:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 
0.10.0-alpha.5

* **OS and version:** 
Ubuntu 16.04
```
g    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

@angular/cli: 1.2.0
node: 7.10.0
os: linux x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/upgrade: 4.1.3
```

* **Browser:** Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by mathisscott** [comment]
@bashibozuk 
Please make sure you have Chrome Canary installed on your machine. The tests use HeadlessChrome (included with Chrome Canary) to run the tests.

**Comment by bashibozuk** [comment]
You cant have Chrome Canary on Linux - https://askubuntu.com/questions/309813/how-to-have-ubuntu-chrome-canary
And in my opinion a developer should be able to run clarity tests on Linux also on Windows.
ng test command runs on any OS for example. Could you please explain why the reason I am getting error with no message is that I am using Headless Chrome instead of Chrome Canary ?

**Comment by mathisscott** [comment]
@bashibozuk 
Headless Chrome is part of Chrome Canary at this time.

As for Linux and Windows, @jeeyun might be able to advise there...

**Comment by jeeyun** [comment]
Hi @bashibozuk, 
Can you change the following line in your local `karma.conf.js`:

`  browsers: ["Chrome_Canary_Headless"],`

to:

`  browsers: ["Chrome_Headless"],`

And see if you are able to run the test locally on Linux?

I agree with you that our scripts should allow running tests locally on any OS. At the time I wrote the script, Chrome only supported headless in Canary in some OSs while it was already supported in Linux. I made a team-centric choice in the script since all of our team members were able to use Chrome Canary to run tests locally. I just did a quick check, and it seems that the latest versions of Chrome support headless in Linux/Windows/Mac, so I will update our script accordingly.
