### ISSUE TITLE
[NG] No provider for VerticalNavIconService

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1552]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

`VerticalNavIconService` should be provided by `ClarityModule` if needed while i don't understand why a internal Service is needed by Karma anyway.

### Actual behavior

Jasmine throws: `No provider for VerticalNavIconService!`
```
Error: No provider for VerticalNavIconService!
    at injectionError (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:1169:22)
    at noProviderError (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:1207:1)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:2649:1)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKeyDefault (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:2688:1)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKey (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:2620:1)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_.get (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:2489:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:9489:1)
    at NgModuleRef_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleRef_.get (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:10577:1)
    at resolveDep (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:11080:1)
    at createClass (http://localhost:9876/_karma_webpack_/webpack:/Users/marvinosswald/dev/svg/mysvg-frontend/node_modules/@angular/core/@angular/core.es5.js:10933:1)
```

Before restructuring to webpack i could just provide the service from `node_modules`, but now that doesn't contain sources anymore only the compiled dist. 

### Reproduction of behavior
I've tried reproducing that issue with an plunkr, but with jasmine only it all works for some reasons..

### Environment details

* **Angular version:** 4.3.x

* **Clarity version:** 0.10.8

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@marvinosswald: I don't believe thats the `VerticalNavIconService` should be exported with the `ClarityModule`. Its an internal service used by the Vertical Nav. Why do you need access to that?

**Comment by adityarb88** [comment]
cc: @hippee-lee @jeeyun

**Comment by hippee-lee** [comment]
I'll check with the clarity-seed and see if I can reproduce it there.

**Comment by hippee-lee** [comment]
Hi @marvinosswald 
I tried to recreate the testing issue with [Clarity Seed](https://github.com/vmware/clarity-seed). Here are the steps I took:z

1. I updated and installed Clarity v0.10.8
2. Added a simple Vertical Nav component to the app
3. Ran the project tests

This did  not reproduce the error. Is this project's test setup similar to your karma.conf.js?
Is there anything else you can tell me about your projects configuration that will help me reproduce this error?

**Comment by marvinosswald** [comment]
@adityarb88 me neither but my angular-cli test is asking for it, that it shouldn't ask for it in the first place is absolute true.

**Comment by marvinosswald** [comment]
@hippee-lee thing is i didn't use the seed i've used a cli generated project and then installed clarity on top of it. But i've just did that same thing again and now i can't reproduce it in there myself, though the issue still exists on my real project. But until i can't reproduce it myself i will close it here as is obviously has something to do with my project setup.

**Comment by baio** [comment]
Hi guys as for v0.12.9
VerticalNavService - is imported inside ClrVerticalNav (not ClarityModule), and it give error above in some cases, for example it will give No provider for VerticalNavIconService!

```
<clr-vertical-nav
    [clr-nav-level]="1"
    [clrVerticalNavCollapsible]="true"
    [(clrVerticalNavCollapsed)]="collapsed">

    <ng-container *ngFor="let item of items">
        <clr-vertical-nav-group
            *ngIf="item.children"
            routerLinkActive="active"
            [clrVerticalNavGroupExpanded]="true">

            <ng-container *ngTemplateOutlet="wrapItem; context: {$implicit: item}"></ng-container>

            <clr-vertical-nav-group-children *clrIfExpanded>
                <ng-container *ngFor="let child of item.children">
                    <ng-container *ngTemplateOutlet="wrapItem; context: {$implicit: child}"></ng-container>
                </ng-container>
            </clr-vertical-nav-group-children>

        </clr-vertical-nav-group>
        <clr-vertical-nav
            *ngIf="!item.children"
            routerLinkActive="active">
            <ng-container *ngTemplateOutlet="wrapItem; context: {$implicit: item}"></ng-container>

        </clr-vertical-nav>
    </ng-container>

</clr-vertical-nav>

<ng-template
    #wrapItem
    let-item>
    <a
        *ngIf="item.path"
        aria-hidden="true"
        clrVerticalNavLink
        [routerLink]="item.path">
        <ng-container *ngTemplateOutlet="citem; context: {$implicit: item}"></ng-container>
    </a>
    <ng-container *ngIf="!item.path">
        <ng-container *ngTemplateOutlet="citem; context: {$implicit: item}"></ng-container>
    </ng-container>

</ng-template>

<ng-template
    #citem
    let-item>
    <clr-icon
        clrVerticalNavIcon
        *ngIf="item.icon"
        [attr.shape]="item.icon"></clr-icon>
    {{item.title}}
</ng-template>

```

**Comment by hippee-lee** [comment]
Hi @baio - this sounds like an implementation question. Please ask those kinds of questions on StackOverflow and tag it with the `vmware-clarity` tag so we can address it there. That way the community benefits from the Q&A. 

It will help if you can reproduce your issue in minimal form using something like Stackblitz. Here is a minimal Clarity app on Stackblitz to get you started. https://stackblitz.com/edit/clarity-light-theme-v012-5roec7
