### ISSUE TITLE
Aot build failed in angular5

### ISSUE THREAD

**Issue by changev** [vmware/clarity#1864]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Aot build success

### Actual behavior

aot build failed
```
ERROR in ./node_modules/@clr/icons/index.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:9432:18)
    at assignContextualParameterTypes (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:37839:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:38136:29)
    at checkExpressionWorker (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:39148:28)
    at checkExpression (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:39077:42)
    at checkBinaryLikeExpression (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:38657:29)
    at checkBinaryExpression (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:38649:20)
    at checkExpressionWorker (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:39169:28)
    at checkExpression (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:39077:42)
    at checkExpressionStatement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:41199:13)
    at checkSourceElement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43009:28)
    at Object.forEach (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:1500:30)
    at checkBlock (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:40794:16)
    at checkSourceElement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43005:28)
    at checkIfStatement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:41205:13)
    at checkSourceElement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43011:28)
    at Object.forEach (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:1500:30)
    at checkBlock (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:40794:16)
    at checkSourceElement (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43005:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:38178:21)
    at checkDeferredNodes (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43091:25)
    at checkSourceFileWorker (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43126:17)
    at checkSourceFile (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43105:13)
    at Object.forEach (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:1500:30)
    at getDiagnosticsWorker (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43187:16)
    at getDiagnostics (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:43155:24)
    at Object.getEmitResolver (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:23078:13)
    at emitWorker (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:70238:69)
    at C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:70203:66
    at runWithCancellationToken (C:\Users\weia4\workspace\ui\node_modules\typescript\lib\typescript.js:70295:24)
 @ ./src/app/app.component.ts 4:0-42
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
```

### Reproduction of behavior
I create a service to inject ClarityIcons and import it in app.module
```
import { Injectable } from '@angular/core';
import { ClarityIcons } from '@clr/icons';
import { EssentialShapes } from "@clr/icons/shapes/essential-shapes";
import { SocialShapes } from "@clr/icons/shapes/social-shapes";
import { TechnologyShapes } from "@clr/icons/shapes/technology-shapes";

/**
 * ClarityIcons, for add new customized icons.
 * Usually it won't be injected by any component.
 */
@Injectable()
export class IconService {
    constructor(){}

    // example icons
    icons : any = {}

    // this function must be ran once in root component or root component for init clarity-icons
    public load(){
          ClarityIcons.add(EssentialShapes);
          ClarityIcons.add(SocialShapes);
          ClarityIcons.add(TechnologyShapes);
          ClarityIcons.add(this.icons);
    }
}

```

### Environment details

* **Angular version:** 5.1.0

* **Clarity version: 0.11

* **OS and version: windows 10/ git bash

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by changev** [comment]
I fixed this after upgrading typescript to 2.6.1.

**Comment by gnomeontherun** [comment]
What version did you have prior to upgrading? Angular 5 requires at least 2.4.2.

**Comment by changev** [comment]
@gnomeontherun I use 2.4.2 before
