### ISSUE TITLE
0.12.0-beta3 gets internal error when building with AoT

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#2309]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
Get internal error when building.

### Reproduction of behavior
Build with AoT and you get:

```
ERROR in : Error: Internal error: unknown identifier undefined
    at Object.importExpr$$1 [as importExpr] (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:20493:23)
    at tokenExpr (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:11721:39)
    at providerDef (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:11647:20)
    at ViewBuilder._visitProviderOrDirective (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16848:18)
    at ViewBuilder._visitProvider (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16809:36)
    at D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16672:23
    at Array.forEach (<anonymous>)
    at ViewBuilder._visitElementOrTemplate (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16657:23)
    at ViewBuilder.visitElement (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16577:23)
    at ElementAst.visit (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:563:24)
    at visit (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:768:37)
    at D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:770:25
    at Array.forEach (<anonymous>)
    at templateVisitAll (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:769:10)
    at ViewBuilder.visitAll (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16450:9)
    at ViewCompiler.compileComponent (D:\Git\vra74\core\branding\navigation\node_modules\@angular\compiler\bundles\compiler.umd.js:16385:17)
```

### Environment details

* **Angular version:** 6.0.2

* **Clarity version:** 0.12.0-beta3

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
I haven't been able to isolate why this happens given your codebase, it compiles fine in other examples I have. If you have a chance to do any experimentation with what could be this ill-defined error please let us know, otherwise I'll keep looking as I have time.

**Comment by rbirkgit** [comment]
I reproduced this with a clean Angular-CLI project. All I did was adding Clarity to it. I will send you my code.

**Comment by gnomeontherun** [comment]
Can you please try again with beta-4?

**Comment by rbirkgit** [comment]
Works in the angular-cli project. Will test next with out full project!

**Comment by rbirkgit** [comment]
Tested full project and it builds! Also tested running it and so far looking good!

**Comment by gnomeontherun** [comment]
Great, will close this issue and thanks for checking things!

**Comment by eymriseFrance** [comment]
Hello good evening sorry for some error i got my amnesia with my code but im a member:))
