### ISSUE TITLE
Incompatible with Angular Universal

### ISSUE THREAD

**Issue by etherwizard** [vmware/clarity#3490]
Please assist.

_macOS 10.14.5_

### STEPS TO RECREATE:

```
npm install -g @angular/cli
npm install -g typescript

ng new my-angular-project
cd my-angular-project
ng add @clr/angular
ng add @nguniversal/express-engine --clientProject my-angular-project
```

**package.json** contents:

```
{
  "name": "my-angular-project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run my-angular-project:server:production"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.1",
    "@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/forms": "~8.0.1",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/platform-server": "~8.0.1",
    "@angular/router": "~8.0.1",
    "@clr/angular": "^2.0.1",
    "@clr/icons": "2.0.1",
    "@clr/ui": "2.0.1",
    "@nguniversal/express-engine": "^7.0.2",
    "@nguniversal/module-map-ngfactory-loader": "v7.0.2",
    "@webcomponents/custom-elements": "^1.0.0",
    "express": "^4.15.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.3",
    "@angular/compiler-cli": "~8.0.1",
    "@angular/language-service": "~8.0.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack-cli": "^3.1.0"
  }
}
```

**Begin local rendering of Angular Universal** (per [angular.io](https://angular.io/guide/universal)):

`npm run build:ssr && npm run serve:ssr`

### RESULT:

```
/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:156617
        Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [KeyboardEvent]),
                                                                                       ^

ReferenceError: KeyboardEvent is not defined
    at /Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:156617:88
    at Module.<anonymous> (/User/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:156628:2)
    at __webpack_require__ (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:20:30)
    at Object.@clr/angular (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:140071:18)
    at __webpack_require__ (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:137858:30)
    at Module../node_modules/@clr/angular/clr-angular.ngfactory.js (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:138363:70)
    at __webpack_require__ (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:137858:30)
    at Module../src/app/app.server.module.ngfactory.js (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:139824:105)
    at __webpack_require__ (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:137858:30)
    at Module../src/main.server.ts (/Users/AwesomeClarityFan/Projects/my-angular-project/dist/server.js:139921:90)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-angular-project@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-angular-project@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AwesomeClarityFan/.npm/_logs/2019-06-21T02_13_22_915Z-debug.log
```

**Complete log pasted:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve:ssr' ]
2 info using npm@6.7.0
3 info using node@v11.12.0
4 verbose run-script [ 'preserve:ssr', 'serve:ssr', 'postserve:ssr' ]
5 info lifecycle my-angular-project@0.0.0~preserve:ssr: my-angular-project@0.0.0
6 info lifecycle my-angular-project@0.0.0~serve:ssr: my-angular-project@0.0.0
7 verbose lifecycle my-angular-project@0.0.0~serve:ssr: unsafe-perm in lifecycle true
8 verbose lifecycle my-angular-project@0.0.0~serve:ssr: PATH: [ ... snip ... ]
9 verbose lifecycle my-angular-project@0.0.0~serve:ssr: CWD: /Users/AwesomeClarityFan/Projects/my-angular-project
10 silly lifecycle my-angular-project@0.0.0~serve:ssr: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle my-angular-project@0.0.0~serve:ssr: Returned: code: 1  signal: null
12 info lifecycle my-angular-project@0.0.0~serve:ssr: Failed to exec serve:ssr script
13 verbose stack Error: my-angular-project@0.0.0 serve:ssr: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:988:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid my-angular-project@0.0.0
15 verbose cwd /Users/AwesomeClarityFan/Projects/my-angular-project
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve:ssr"
18 verbose node v11.12.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-angular-project@0.0.0 serve:ssr: `node dist/server`
22 error Exit status 1
23 error Failed at the my-angular-project@0.0.0 serve:ssr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hippee-lee** [comment]
This looks like a known issue related to typing `@HostListener` events. I'm not sure why we didn't have this issue before upgrading to Angular8 and will need to investigate more. In the mean time, I created a demo workaround project seems to work with a modified `server.ts`. The relevant changes for `server.ts` are shown here. https://github.com/hippee-lee/3940-v8-ssr/blob/master/server.ts#L29

**Comment by hippee-lee** [comment]
I'm adding the bug label to this for now. One `fix` would be to remove the event type and replace it with `any`. I'd rather not unless we absolutely have to. 

### Current Form(broken)
```
  @HostListener('keydown', ['$event'])
  onKeyDown(event: KeyboardEvent) {
    /* event handler code */
  }
```

### potential (but undesirable) fix
```
  @HostListener('keydown', ['$event'])
  onKeyDown(event: any) {
    /* event handler code */
  }
```

**Comment by etherwizard** [comment]
Thanks. After implementing that change to **server.ts** I can confirm that Angular Universal runs without build errors.

**Comment by gnomeontherun** [comment]
Closing this as resolved. If a similar issue appears let's open a new issue with an updated example.
