### ISSUE TITLE
Missing dependencies error

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#5498]
## Describe the bug

```
I'm getting an error after upgrading from v4 to v5 then running `ng serve`.
An unhandled exception occurred: The target entry-point "@clr/angular" has missing dependencies:
 - @cds/core/icon
 - @cds/core/icon/register
```
Installed packages:
```
"@clr/angular": "^5.0.0",
"@clr/core": "^4.0.10",
"@clr/icons": "^5.0.0",
"@clr/ui": "^5.0.0",
```
## How to reproduce

1. Upgrade from v4 to v5.
2. Run `ng serve`.

## Expected behavior

Should not have an error when running `ng serve`

## Versions

**App**

- Angular: 11
- Node: 12+
- Clarity: v5

**Device:**

- Type: Intel NUC
- OS: Windows 10 Enterprise
- Browser: Chrome
- Version: 87/88

## Additional notes

`at TargetedEntryPointFinder.findEntryPoints (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:28:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@ngtools\webpack\src\ngcc_processor.js:163:16)
    at C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@ngtools\webpack\src\ivy\host.js:55:18
    at C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@ngtools\webpack\src\ivy\host.js:47:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@ngtools\webpack\src\ivy\host.js:45:32)
    at actualResolveModuleNamesWorker (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\typescript\lib\typescript.js:105298:133)
    at resolveModuleNamesWorker (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\typescript\lib\typescript.js:105536:26)
    at resolveModuleNamesReusingOldState (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\typescript\lib\typescript.js:105650:24)`

**Comment by wendellestradairely** [comment]
Fixed by installing
"@cds/angular": "^5.0.0",
"@cds/core": "^5.0.0",

**Comment by gnomeontherun** [comment]
Thanks for the update, in the future you can run `ng update @clr/angular` and it will process our schematics that would have installed those dependencies for you.

**Comment by rogerfar** [comment]
@gnomeontherun I updated today but it didn't install any missing schematics. 

Now that NPM upgrades you to 5.0 I think a lot of users will experience this issue.

Also the docs still say that @clr/icons should be enough. Is there an official upgrade from 4 to 5 somewhere? I'm confused to what I'm supposed to use, like what is the difference between @clr/angular vs @cds/angular? Do I need both? What if I need icons?

**Comment by gnomeontherun** [comment]
@cds/angular is the Angular wrapper for Clarity Core. This basically registers the web components in a way that the Angular compiler understands. It does not provide the traditional Clarity Angular components.

If you are using just Clarity Angular, with v5 you should have
* @clr/angular
* @clr/ui
* @cds/core (icons are found inside @cds/core/icon, but you can still use @clr/icon if you have them)

We have a blog post about icons coming to explain some of the transition details, but the schematic should have handled installing Core for you (nothing else really).

**Comment by rogerfar** [comment]
Ok I'll wait with the upgrade until there is more documentation. I tried v5 but there's something up with my icons, some got much bigger, some much smaller.

**Comment by gnomeontherun** [comment]
Please provide feedback if you have issues on specifics so we can triage, and make a new issue please.
