### ISSUE TITLE
Parse error (unexpected token) when testing @cds/core using jest due to a named import

### ISSUE THREAD

**Issue by antgamdia** [vmware/clarity#6106]
## Describe the bug

In Kubeapps (VMware) we are using Clarity as the design framework and we wanted to upgrade from Clarity `5.1.x` to `>=5.2.x`. It should be a big deal, as it's just a minor version upgrade. However, in that version, you updated `lit` to v2 (which is totally fine) and it is making our Jest tests fail somehow.

The detailed report is here: https://github.com/kubeapps/kubeapps/pull/3042#issuecomment-870053634

The root issue might be on our side, so this issue is just intended to ask whether adding the following fix[1]  is something doable:

## How to reproduce

Unfortunately, I haven't had a chance to create a reproducible scenario. I'll try to do that if you really need it.

1.  Download the latest `@cds/core` version. For the sake of this example, let's do it manually:
```console
wget `npm v @cds/core dist.tarball` && tar -xOzf core-5.4.1.tgz package/icon/collections/essential.js | grep  "as as"
```

2. The file `package/icon/collections/essential.js` contains something like:
```js
;import{historyIcon as as}from"../shapes/history.js"
```

3. [Note, using `as` as a named import is absolutely fine indeed, but some parsers aren't able to deal with it]

When running the tests (`yarn test`) it complains:

```console
SyntaxError: /home/agamez/Desktop/kubeapps/dashboard/node_modules/@cds/core/icon/collections/essential.js: Unexpected token, expected "," (1:3239)

    > 58 | import{historyIcon as as}from"../shapes/history.js";
         |                    ^

      at Object._raise (node_modules/@babel/parser/src/parser/error.js:97:45)
      at Object.raiseWithData (node_modules/@babel/parser/src/parser/error.js:92:17)
      at Object.raise (node_modules/@babel/parser/src/parser/error.js:41:17)
      at Object.unexpected (node_modules/@babel/parser/src/parser/util.js:161:16)
      at Object.expect (node_modules/@babel/parser/src/parser/util.js:138:28)
      at Object.parseNamedImportSpecifiers (node_modules/@babel/parser/src/parser/statement.js:2364:14)
      at Object.parseImport (node_modules/@babel/parser/src/parser/statement.js:2145:39)
      at Object.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:265:25)
      at Object.parseStatement (node_modules/@babel/parser/src/parser/statement.js:176:17)
      at Object.parseStatement (node_modules/@babel/parser/src/plugins/flow/index.js:1815:26)
```

4. When manually replacing  `import{historyIcon as as}from"../shapes/history.js";` by  `import{historyIcon as whaaaatever}from"../shapes/history.js";` it works! The tests pass and everything is fine.
  - This workaround is depicted in https://github.com/kubeapps/kubeapps/pull/3042/commits/86a7aa59fd4fecff33f1d55ddebecd4b3e5ce9bf

## Expected behavior

I would expect not to have this parse error :(

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [X] React
- [ ] Vue
- [ ] Other:

**Framework version:**
React 16, Babel transitive dependencies introduced by `react-scripts` 4.0.3 (I guess it's `@babel/core@7.12.3`)

**Device:**

N/A (it appears in both local dev env and in the container image)

## Additional notes

Similar to https://github.com/vmware/clarity/issues/5672 (but do use `transformIgnorePatterns`, it's not the issue here)

[1] So, my question is: is it possible for you, when generating a newly built package, to avoid using named import using js tokens like `as`? If not, at least, do you know a way to achieve it using Babel? (even if we had to run Babel to modify your code when testing)?

Edit: I'm getting closer to the root cause... it seems a `react-script` misconfiguration when using the parser in the module `babel-preset-react-app`. Adding `flow:false` seems prevents this issue to appear.

I ended up creating an upstream issue: https://github.com/babel/babel/issues/13520

Feel free to close the issue, but I just wanted to let you know about this error we're having if other people use Clarity with React and Jest.

**Comment by mathisscott** [comment]
@antgamdia 
Thanks for submitting the issue and digging deeper into the root cause. This is good information to have!
