### ISSUE TITLE
Not able to create clarity-wizard-step s dynamically

### ISSUE THREAD

**Issue by indukr** [vmware/clarity#742]
**Select one ...**  (check one with "x")
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
Should be able to iterate through an array of objects and should be able to create wizard steps dynamically

### Actual behavior
Not able to create the wizard steps dynamically using "clarity-wizard-step"

### Reproduction of behavior
Should try to create wizard steps dynamically . I am trying something similar to the one below
<clr-wizard-step *ngFor="let step of [1,2,3]">
Step {{ step }}
<clr-wizard-step>

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:**  0.8.11

* **OS and version:**  Windows 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Works for me.

https://plnkr.co/edit/lJ4M0NqsxPV2XdXbhBAw?p=preview

**Comment by indukr** [comment]
Hi mathiscott,

Getting the following UI error in plunker.  What is this error abt and how to resolve it :

editor-1.0.0.js:2 URL visited /lJ4M0NqsxPV2XdXbhBAw?p=preview
static.ads-twitter.com/oct.js Failed to load resource: the server responded with a status of 403 (Forbidden)
unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3491 EXCEPTION: Error in app/app.component.html:15:4 caused by: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'clr-wizard-0-tab-0'.
ErrorHandler.handleError @ unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3491
unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3493 ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'clr-wizard-0-tab-0'.
ErrorHandler.handleError @ unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3493
unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3496 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3496
unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:3497 Error: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'clr-wizard-0-tab-0'.
    at ExpressionChangedAfterItHasBeenCheckedError.BaseError [as constructor] (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:1225:31) [angular]
    at new ExpressionChangedAfterItHasBeenCheckedError (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:6554:20) [angular]
    at checkBinding (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:6729:23) [angular]
    at Wrapper_WizardStep.checkHost (/ClarityModule/WizardStep/wrapper.ngfactory.js:67:7) [angular]
    at View_AppComponent1.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:343:24) [angular]
    at View_AppComponent1.AppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12592:18) [angular]
    at View_AppComponent1.DebugAppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12739:48) [angular]
    at ViewContainer.detectChangesInNestedViews (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12850:41) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:196:15) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12592:18) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12739:48) [angular]
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12577:22) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (https://unpkg.com/@angular/core@2.4.1/bundles/core.umd.js:12592:18) [angular]

**Comment by mathisscott** [comment]
@indukr

Without seeing exactly what you are trying to do in plunkr, I can't say. Plunkr is working fine for me with no errors. 

From the looks of the error you pasted, it appears you either caught plunkr at a bad time. Or perhaps you have a firewall blocking access to it?

Not really sure. Give it another try to see if The errors persist

**Comment by indukr** [comment]
@mathisscott  

Thank you so much for your quick response.

Its in the same plunker that you gave as below:

https://plnkr.co/edit/lJ4M0NqsxPV2XdXbhBAw?p=preview

when I see console in developer tools, I can find the  above error(This error comes during the page load). But able to load wizard with the button click provided.

And is it possible to load the wizard directly without the button click event? I tried removing the button in the plunker above and setting 'clrWizardOpen' attribute of <clr-wizard> to 'true'. But not able to open the wizard on page load.

**Comment by mathisscott** [comment]
@indukr
I'm still not seeing the error you are describing. Not in Safari or Chrome. What browser are you using?

And yes you should be able to set clrWizardOpen to true to bypass needing to click a button.

**Comment by indukr** [comment]
@mathisscott  I am also using chrome (version: 57.0.2987.133). But could still see the same error in my console log. Does it have any thing to do with the version?  If not it could be due to my firewall settings.

Able to bypass button click event by setting clrWizardOpen to true. Thanks for the info.

**Comment by mathisscott** [comment]
@indukr : I don't think it has anything to do with the version. You're getting a 403. I'll keep an ear out for similar issues. But at this point, you would be best served by trying to work outside of Plunkr.

**Comment by indukr** [comment]
@mathisscott Sure thanks..
